apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    env: prod
spec:
  selector:
    env: prod
  type: NodePort
  ports:
  - nodePort: 30001
    targetPort: 80
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  labels:
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      name: myapp-pod
      labels:
        env: prod
    spec:
      containers:
      - name: myapp-con
        image: gautam191/apache:v1
        ports:
        - containerPort: 80






